### ISSUE TITLE
array values endpoint, sync endpoint

### ISSUE THREAD

**Issue by j-forster** [Waziup/waziup-api#18]
For synchronization mechanisms with the Gateway, an endpoint is required that allows the upload of multiple separated data points. This can be achieved with multiple calls to the `POST devices/xxx/sensors/yyy/value` endpoint, what is a very inefficient solution.

Based on the `/value` endpoint (see the [swagger spec.](https://api.waziup.io/docs/#/Sensors/post_devices__device_id__sensors__sensor_id__value)), the `/values` should be like:

Headers:
 - Content-Type: `application/json`

Body: array of data points, can have length 0, ordered by timestamp (ascending, latest value last)
Data Point: a {Value,Timestamp} Object
Value: required, any type, not null
Timestamp: required, timestamp (JavaScript Date)

Example:

```json
[{
  "value": 25,
  "timestamp": "2016-06-08T18:00:00.000Z"
},{
  "value": 27,
  "timestamp": "2016-06-08T19:00:00.000Z"
},{
  "value": 24,
  "timestamp": "2016-06-08T20:00:00.000Z"
}]
```

Note that the API implementation might require to only submit values that are newer than the existing values at the API database. This might prevent the upload of values from the past when there are newer data points present.

**Comment by cdupont** [comment]
I think that the datapoints probably don't need to be sorted.
I think you could upload data from any timeframe (even in the past, while more recent datapoints are present).
However, how to avoid doubles? should we check the timestamps? Or permit to transmit a datapoint ID as well, to ensure unicity?

**Comment by j-forster** [comment]
The idea behind this constraint is to allow different database algorithms for the API server.
In the future, a solution based on a flat binary storage might give use the best performance and storage efficiency that we will definitely need at some point. This binary storage might not be able to add values _in between_ but only in ascending order for multiple reasons.

Besides that, there is no practical need for adding historical values behind existing values. Sensor values are timestamped and the Gateway does sync with sequential values only.

**Comment by cdupont** [comment]
Shall MQTT follow the same principle? How will it work?

**Comment by cdupont** [comment]
How do you identify datapoints that has already been uploaded (for avoiding re-uploading them)?

**Comment by cdupont** [comment]
In the Cloud server, when a single datapoint is posted on `/devices/{device_id}/sensors/{sensor_id}/value`, here is what happens:
1. access rights are checked for writing on the specific device
2. value is posted in Orion as the "last value" attribute
3. datapoint is added in the Mongo DB history
4. datapoint is published on MQTT server

Point 1. should not be a problem for `/values` as well.
Regarding 2., it's not clear for me if posting on the /values should also update the "last value", that should be stored in Orion. This value is important because this is the one displayed on the Dashboard and used to trigger notifications (SMS, Twitter etc.). 
For point 3., all datapoints should be added in the Mongo DB, but how to check doubles?
For point 4, not sure what to do. It seems to me that MQTT needs to handle the messages one by one (one PUBLISH for each datapoints), not all at once.

**Comment by j-forster** [comment]
Yes, MQTT has the same endpoints as REST. It's the same functionality. 

> In the Cloud server, when a single datapoint is posted on `/devices/{device_id}/sensors/{sensor_id}/value`, here is what happens:
> 
> 1. access rights are checked for writing on the specific device
> 2. value is posted in Orion as the "last value" attribute
> 3. datapoint is added in the Mongo DB history
> 4. datapoint is published on MQTT server

The [Gateway API](https://godoc.org/gopkg.in/waziup/wazigate-edge.v2/edge#PostSensorValues) has the function [PostSensorValues](https://godoc.org/gopkg.in/waziup/wazigate-edge.v2/edge#PostSensorValues), that does exactly the same:
(Source: https://github.com/Waziup/wazigate-edge/blob/v2.5/edge/sensor.go#L218)

1.  (permission checks are missing on the GW)
2. The Devices database gets the last value (which is also the latest value)
3. All values are added in the Mongo DB history (which might be replaced by the flat binary storage)
4. MQTT is done automatically for all endpoints

Duplicate times are allowed, as the MongoDB dates format are with a accuracy of microseconds and there might be cases where a more detailed time is needed.

You don't need to implement the `/values` for MQTT now, as MQTT (for the sync manager) is for subscribing to actuators only. All the upstream sync of sensor values and declaration of devices, sensors and actuators is done using REST. But I might easily switch to MQTT if all endpoints on the cloud can be served with MQTT.

**Comment by cdupont** [comment]
I did a quick implementation of `/values`: https://api.waziup.io/docs/#/Sensors/post_devices__device_id__sensors__sensor_id__values
Please check it out.

**Comment by j-forster** [comment]
The gateway sync that uses the `/values` endpoint is now working flawlessly and I can see all the values at the cloud dashboard 👍 
Thanks @cdupont !
