### ISSUE TITLE
umlaut names not supported

### ISSUE THREAD

**Issue by j-forster** [Waziup/waziup-api#23]
The following API call fails, most likely because of the umlaut letter "ä":

```javascript
await fetch("https://api.waziup.io/api/v2/devices/MyGuestSensor/sensors/TC/value", {
	method: "POST",
	headers: {
		"Content-Type": "application/json; charset=UTF-8"
    },
    body: JSON.stringify({
		value: "Hällo",
		timestamp: new Date()
    })
});
```
Returns: 500 Something went wrong

Without the umlaut there are no problems.

**Comment by cdupont** [comment]
Fixed: https://github.com/Waziup/waziup-api/commit/5fdd9f103009f592a4319d01013d9735f7481807
